# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
#     - name: Cache Closure Compiler
#       id: cache-closure
#       uses: actions/cache@v2
#       with:
#         path: |
#           closure-compiler-*.jar
#         key: ${{ runner.os }}--forever
    - name: Get Closure Compiler
#       if: steps.cache-closure.outputs.cache-hit != 'true'
      run: |
        echo +--Getting Closure Compiler--+
        npm install --save google-closure-compiler
    - name: Dry Compile
      run: |
        echo +--Dry Compiling--+
        npx google-closure-compiler --js *.js
